# Generated by Django 2.2.1 on 2019-06-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finereport',
            old_name='patron',
            new_name='patrons',
        ),
        migrations.RenameField(
            model_name='noduecertificate',
            old_name='patron',
            new_name='patrons',
        ),
    ]
