# Generated by Django 2.2.1 on 2019-06-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190529_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDueCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.IntegerField(blank=True)),
                ('ref_number', models.IntegerField(blank=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_due_certificate', to='portal.Borrowers')),
            ],
        ),
    ]
