# Generated by Django 2.2.1 on 2019-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_nodueaddressee_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodueaddressee',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
