# Generated by Django 2.2.1 on 2019-06-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190621_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patroninfo',
            name='ref_number',
        ),
        migrations.AddField(
            model_name='patroninfo',
            name='fine_ref_number',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patroninfo',
            name='ndc_ref_number',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
