# Generated by Django 2.2.1 on 2019-06-18 04:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_noduecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDueAddressee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
