# Generated by Django 2.2.1 on 2019-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190619_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='noduecertificate',
            name='full_ref',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
