# Generated by Django 2.2.1 on 2019-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190618_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noduecertificate',
            name='mem_number',
            field=models.CharField(max_length=20),
        ),
    ]
