# Generated by Django 2.2.1 on 2019-06-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_noduecertificate_full_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.IntegerField(blank=True)),
                ('patron_name', models.CharField(max_length=50)),
                ('ic_number', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('mem_number', models.CharField(max_length=20)),
                ('ref_number', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('full_ref', models.CharField(max_length=40, null=True)),
                ('addressee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_reports', to='portal.NoDueAddressee')),
            ],
            options={
                'db_table': 'fine_report',
            },
        ),
    ]
