# Generated by Django 2.2.1 on 2019-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190621_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereportsummary',
            name='unit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
