# Generated by Django 2.2.1 on 2019-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190618_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodueaddressee',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
