# Generated by Django 2.2.1 on 2019-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_finereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereport',
            name='fine',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
