# Generated by Django 2.2.1 on 2019-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_finereportsummary_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereportsummary',
            name='from_date',
            field=models.DateField(default='2019-01-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finereportsummary',
            name='to_date',
            field=models.DateField(default='2019-01-11'),
            preserve_default=False,
        ),
    ]
