# Generated by Django 2.2.1 on 2019-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190618_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='noduecertificate',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
