# Generated by Django 2.2.1 on 2019-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_noduecertificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='noduecertificate',
            name='addressee_content',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
